CLY_vanilla_locations =
[
	[CLY_vanilla_abdera, "Abdera", 5, 12, "CLY_loadout_ar_i", [CLY_vanilla_abdera_bad1, CLY_vanilla_abdera_bad2]],
	[CLY_vanilla_aggelochori, "Aggelochori", 16, 40, "CLY_loadout_random_i"],
	[CLY_vanilla_aggelochoriConstructionYard, "Aggelochori construction yard", 2, 3, "srifle_LRR_F", [CLY_vanilla_aggelochoriConstructionYard_bad1, CLY_vanilla_aggelochoriConstructionYard_bad2]],
	[CLY_vanilla_aggelochoriDepot, "Aggelochori depot", 2, 2, "CLY_loadout_hg_l"],
	[CLY_vanilla_aggelochoriResort, "Aggelochori resort", 3, 6, "hgun_ACPC2_F"],
	[CLY_vanilla_agiosDionysios, "Agios Dionysios", 12, 30, "CLY_loadout_random", [CLY_vanilla_agiosDionysios_bad1, CLY_vanilla_agiosDionysios_bad2]],
	[CLY_vanilla_agiosDionysiosJunkyard, "Agios Dionysios junkyard", 2, 3, "hgun_ACPC2_F"],
	[CLY_vanilla_agiosKonstantinos, "Agios Konstantinos", 6, 14, "CLY_loadout_ar_i"],
	[CLY_vanilla_agiosTheodoros, "Agios Theodoros", 2, 4, "SMG_01_F", [CLY_vanilla_agiosTheodoros_bad1, CLY_vanilla_agiosTheodoros_bad2, CLY_vanilla_agiosTheodoros_bad3, CLY_vanilla_agiosTheodoros_bad4, CLY_vanilla_agiosTheodoros_bad5]],
	[CLY_vanilla_aktinarki, "Aktinarki ruins", 2, 5, ["CLY_loadout_ar_i", "CLY_loadout_hg_l"], [CLY_vanilla_aktinarki_bad1, CLY_vanilla_aktinarki_bad2, CLY_vanilla_aktinarki_bad3]],
	[CLY_vanilla_alikampos, "Alikampos", 4, 10, "CLY_loadout_mg"],
	[CLY_vanilla_alikamposConstructionYard, "Alikampos construction yard", 4, 8, "arifle_SDAR_F"],
	[CLY_vanilla_altisInternationalAirport, "Altis International Airport", 2, 6, "CLY_loadout_hg_l"],
	[CLY_vanilla_altisInternationalContainerTerminal, "Altis international container terminal", 4, 10, "CLY_loadout_hg_l"],
	[CLY_vanilla_anthrakia, "Anthrakia", 6, 12, "CLY_loadout_hg_l", [CLY_vanilla_anthrakia_bad1, CLY_vanilla_anthrakia_bad2]],
	[CLY_vanilla_anthrakiaResort, "Anthrakia resort", 3, 5, "hgun_ACPC2_F", [CLY_vanilla_anthrakiaResort_bad1]],
	[CLY_vanilla_athanos, "Athanos", 2, 4, "CLY_loadout_smg_l"],
	[CLY_vanilla_athira, "Athira", 14, 30, "CLY_loadout_random"],
	[CLY_vanilla_athiraIndustrial, "Athira industrial zone", 4, 7, "hgun_ACPC2_F", [CLY_vanilla_athiraIndustrial_bad1, CLY_vanilla_athiraIndustrial_bad2, CLY_vanilla_athiraIndustrial_bad3]],
	[CLY_vanilla_capZefyris, "Cap Zefyris", 2, 4, ["srifle_GM6_F", "hgun_ACPC2_F"]],
	[CLY_vanilla_chalkeia, "Chalkeia", 10, 20, "CLY_loadout_random"],
	[CLY_vanilla_charkia, "Charkia", 12, 30, "CLY_loadout_random_i", [CLY_vanilla_charkia_bad1]],
	[CLY_vanilla_charkiaDepot, "Charkia depot", 5, 12, ["CLY_loadout_hg_l", "CLY_loadout_smg_l_i"], [CLY_vanilla_charkiaDepot_bad1, CLY_vanilla_charkiaDepot_bad2, CLY_vanilla_charkiaDepot_bad3, CLY_vanilla_charkiaDepot_bad4]],
	[CLY_vanilla_dorida, "Dorida", 8, 20, "CLY_loadout_ar_i"],
	[CLY_vanilla_drimea, "Drimea", 2, 2, "SMG_02_F"],
	[CLY_vanilla_edessaPowerPlant, "Edessa power plant", 2, 3, "hgun_ACPC2_F"],
	[CLY_vanilla_feres, "Feres", 10, 25, "CLY_loadout_ar_i"],
	[CLY_vanilla_frini, "Frini", 3, 6, "CLY_loadout_ar_i"],
	[CLY_vanilla_galati, "Galati", 5, 16, "CLY_loadout_smg_l_i"],
	[CLY_vanilla_gravia, "Gravia", 8, 20, "CLY_loadout_random_i"],
	[CLY_vanilla_graviaShantyTown, "Gravia shanty town", 2, 3, ["srifle_GM6_F", "LMG_Zafir_F"]],
	[CLY_vanilla_ifestia, "Ifestia", 2, 4, ["hgun_ACPC2_F", "SMG_01_F", "srifle_EBR_F"], [CLY_vanilla_ifestia_bad1]],
	[CLY_vanilla_ifestiaFarm, "Ifestia farm", 2, 2, "hgun_PDW2000_Holo_snds_F"],
	[CLY_vanilla_ifestiaBase, "Ifestia military base", 4, 8, "CLY_loadout_random", [CLY_vanilla_ifestiaBase_bad1, CLY_vanilla_ifestiaBase_bad2, CLY_vanilla_ifestiaBase_bad3]],
	[CLY_vanilla_ifestiona, "Ifestiona", 2, 5, "srifle_EBR_F"],
	[CLY_vanilla_ioannina, "Ioannina", 2, 4, "CLY_loadout_ar_i"],
	[CLY_vanilla_irakliaValley, "Iraklia valley", 4, 10, ["CLY_loadout_ar_i", "srifle_GM6_F"]],
	[CLY_vanilla_kalithea, "Kalithea", 2, 3, "hgun_PDW2000_Holo_snds_F"],
	[CLY_vanilla_kalitheaHarbor, "Kalithea harbor", 2, 5, ["hgun_ACPC2_F", "srifle_LRR_F"]],
	[CLY_vanilla_kalochori, "Kalochori", 12, 25, "CLY_loadout_ar_i"],
	[CLY_vanilla_katalaki, "Katalaki", 3, 7, "CLY_loadout_ar_i"],
	[CLY_vanilla_kavala, "Kavala", 20, 40, "CLY_loadout_random"],
	[CLY_vanilla_kavalaDepot, "Kavala depot", 2, 5, "CLY_loadout_hg_l", [CLY_vanilla_kavalaDepot_bad1, CLY_vanilla_kavalaDepot_bad2]],
	[CLY_vanilla_kore, "Kore", 5, 16, "CLY_loadout_random_i"],
	[CLY_vanilla_koreDepot, "Kore depot", 2, 5, "arifle_TRG20_F", [CLY_vanilla_koreDepot_bad1, CLY_vanilla_koreDepot_bad2, CLY_vanilla_koreDepot_bad3]],
	[CLY_vanilla_koreIndustrial, "Kore industrial zone", 3, 10, ["CLY_loadout_mr", "hgun_ACPC2_F"], [CLY_vanilla_koreIndustrial_bad1, CLY_vanilla_koreIndustrial_bad2, CLY_vanilla_koreIndustrial_bad3, CLY_vanilla_koreIndustrial_bad4]],
	[CLY_vanilla_kryaNera, "Krya Nera", 2, 3, "CLY_loadout_hg_l"],
	[CLY_vanilla_lakka, "Lakka", 6, 20, "CLY_loadout_random", [CLY_vanilla_lakka_bad1, CLY_vanilla_lakka_bad2, CLY_vanilla_lakka_bad3, CLY_vanilla_lakka_bad4]],
	[CLY_vanilla_lakkaIndustrial, "Lakka industrial zone", 3, 10, ["SMG_01_F", "hgun_ACPC2_F"]],
	[CLY_vanilla_magosPowerPlant, "Magos power plant", 2, 4, "CLY_loadout_hg_l", [CLY_vanilla_magosPowerPlant_bad1, CLY_vanilla_magosPowerPlant_bad2, CLY_vanilla_magosPowerPlant_bad3, CLY_vanilla_magosPowerPlant_bad4]],
	[CLY_vanilla_magosSummit, "Magos summit", 2, 3, "hgun_ACPC2_F"],
	[CLY_vanilla_makrynisi, "Makrynisi", 16, 40, "srifle_GM6_F"],
	[CLY_vanilla_maziBeach, "Mazi beach", 2, 2, "CLY_loadout_hg_l"],
	[CLY_vanilla_mine, "the mine", 2, 4, ["hgun_ACPC2_F", "CLY_loadout_ar_i"]],
	[CLY_vanilla_molos, "Molos", 10, 30, "CLY_loadout_random_i", [CLY_vanilla_molos_bad1, CLY_vanilla_molos_bad2, CLY_vanilla_molos_bad3]],
	[CLY_vanilla_molosResort, "Molos resort", 2, 4, "CLY_loadout_hg_l"],
	[CLY_vanilla_negades, "Negades", 5, 16, "CLY_loadout_random_i", [CLY_vanilla_negades_bad1, CLY_vanilla_negades_bad2, CLY_vanilla_negades_bad3]],
	[CLY_vanilla_neochori, "Neochori", 20, 40, "CLY_loadout_random"],
	[CLY_vanilla_neochoriWest, "Neochori west", 6, 12, "CLY_loadout_smg_l", [CLY_vanilla_neochoriWest_bad1]],
	[CLY_vanilla_neri, "Neri", 5, 10, "CLY_loadout_ar_m_i", [CLY_vanilla_neri_bad1, CLY_vanilla_neri_bad2, CLY_vanilla_neri_bad3]],
	[CLY_vanilla_neriBeach, "Neri beach", 8, 30, "CLY_loadout_ar_i"],
	[CLY_vanilla_neriResort, "Neri resort", 3, 10, "hgun_ACPC2_F", [CLY_vanilla_neriResort_bad1, CLY_vanilla_neriResort_bad2, CLY_vanilla_neriResort_bad3, CLY_vanilla_neriResort_bad4, CLY_vanilla_neriResort_bad5, CLY_vanilla_neriResort_bad6, CLY_vanilla_neriResort_bad7, CLY_vanilla_neriResort_bad8, CLY_vanilla_neriResort_bad9]],
	[CLY_vanilla_nidasosBase, "Nidasos military base", 2, 4, ["srifle_GM6_SOS_F", "CLY_loadout_mr"], [CLY_vanilla_nidasosBase_bad1, CLY_vanilla_nidasosBase_bad2, CLY_vanilla_nidasosBase_bad3, CLY_vanilla_nidasosBase_bad4]],
	[CLY_vanilla_oreokastro, "Oreokastro", 4, 14, "CLY_loadout_ar_i", [CLY_vanilla_oreokastro_bad1, CLY_vanilla_oreokastro_bad2, CLY_vanilla_oreokastro_bad3, CLY_vanilla_oreokastro_bad4]],
	[CLY_vanilla_orino, "Orino", 3, 8, "CLY_loadout_ar_i"],
	[CLY_vanilla_panagia, "Panagia", 7, 12, "srifle_EBR_F"],
	[CLY_vanilla_panagiaEstate, "Panagia estate", 2, 3, "hgun_ACPC2_F"],
	[CLY_vanilla_panochori, "Panochori", 12, 20, "CLY_loadout_random", [CLY_vanilla_panochori_bad1, CLY_vanilla_panochori_bad2, CLY_vanilla_panochori_bad3, CLY_vanilla_panochori_bad4]],
	[CLY_vanilla_paros, "Paros", 16, 40, "CLY_loadout_random", [CLY_vanilla_paros_bad1, CLY_vanilla_paros_bad2]],
	[CLY_vanilla_poliakko, "Poliakko", 5, 12, "CLY_loadout_random_i", [CLY_vanilla_poliakko_bad1]],
	[CLY_vanilla_pyrgos, "Pyrgos", 25, 40, "CLY_loadout_random", [CLY_vanilla_pyrgos_bad1, CLY_vanilla_pyrgos_bad2]],
	[CLY_vanilla_pyrgosBase, "Pyrgos military base", 5, 12, "CLY_loadout_ar_i", [CLY_vanilla_pyrgosBase_bad1, CLY_vanilla_pyrgosBase_bad2]],
	[CLY_vanilla_pyrgosWest, "Pyrgos west", 8, 20, "CLY_loadout_random_i"],
	[CLY_vanilla_rodopoli, "Rodopoli", 8, 25, "CLY_loadout_random"],
	[CLY_vanilla_selakano, "Selakano", 8, 20, "CLY_loadout_ar", [CLY_vanilla_selakano_bad1]],
	[CLY_vanilla_sofia, "Sofia", 12, 25, "CLY_loadout_random"],
	[CLY_vanilla_stavros, "Stavros", 5, 16, "CLY_loadout_random_i", [CLY_vanilla_stavros_bad1]],
	[CLY_vanilla_stavrosDepot, "Stavros depot", 2, 4, "arifle_MXC_F", [CLY_vanilla_stavrosDepot_bad1, CLY_vanilla_stavrosDepot_bad2]],
	[CLY_vanilla_surfClub, "the surf club", 2, 3, "CLY_loadout_hg_l"],
	[CLY_vanilla_syrta, "Syrta", 8, 20, "CLY_loadout_random_i", [CLY_vanilla_syrta_bad1, CLY_vanilla_syrta_bad2]],
	[CLY_vanilla_telos, "Telos", 12, 40, "CLY_loadout_random"],
	[CLY_vanilla_telosBase, "Telos military base", 6, 12, "CLY_loadout_ar_i", [CLY_vanilla_telosBase_bad1, CLY_vanilla_telosBase_bad2, CLY_vanilla_telosBase_bad3, CLY_vanilla_telosBase_bad4, CLY_vanilla_telosBase_bad5, CLY_vanilla_telosBase_bad6, CLY_vanilla_telosBase_bad7, CLY_vanilla_telosBase_bad8]],
	[CLY_vanilla_therisa, "Therisa", 10, 25, "CLY_loadout_random_i", [CLY_vanilla_therisa_bad1, CLY_vanilla_therisa_bad2, CLY_vanilla_therisa_bad3]],
	[CLY_vanilla_therisaConstructionYard, "Therisa construction yard", 2, 3, "CLY_loadout_hg_l"],
	[CLY_vanilla_topolia, "Topolia", 2, 3, ["SMG_01_F", "hgun_ACPC2_F"]],
	[CLY_vanilla_topoliaConstructionYard, "Topolia construction yard", 2, 3, "hgun_ACPC2_F"],
	[CLY_vanilla_topoliaDepot, "Topolia depot", 2, 2, "srifle_LRR_F"],
	[CLY_vanilla_unfinishedStadium, "the unfinished stadium", 2, 3, ["CLY_loadout_hg_l", "hgun_ACPC2_F"], [CLY_vanilla_unfinishedStadium_bad1, CLY_vanilla_unfinishedStadium_bad2]],
	[CLY_vanilla_zaros, "Zaros", 12, 30, "CLY_loadout_random_i", [CLY_vanilla_zaros_bad1]]
];